module Minhash
  # Class for generating Minhash signature
  class Minhash
    attr_reader seed_root: Integer

    def initialize: (?Integer n_hashes, ?Integer seed_root) -> void

    def signature: (Enumerator[String] elems) -> Array[Integer]
  end
end
