module Minhash
  # Class for generating Minhash signature
  class Minhash
    @seed_root: Integer 
    @hashes: Array[^(String) -> Integer]

    attr_reader seed_root: Integer 

    HASH_MAX: Integer

    def initialize: (?Integer n_hashes, ?Integer seed_root) -> void

    # Produces the Minhash signature for a given Set
    #
    # @param set [Set] the set to produce the signature for
    #
    # @return [Array[Integer]] 32 bit integer array of length n_hashes
    def signature: (Set[String] set) -> Array[Integer]
  end
end
