# Shingle a document
module Shingling
  class ShingledDocument
    @document: String

    @k: Integer

    def initialize: (String document, Integer k) -> void

    def each: () ?{ (String) -> untyped } -> (Integer | Set[String])

    private

    def max_index: () -> Integer
  end
end
